---
Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: 'EC2-A1' # keypair must already exist
      ImageId: ami-030001f7dfbf357d1 # AMI us-east-1

# Documentaion
# You can now launch the stack and specify the InstanceType at runtime.
# aws cloudformation create-stack --stack-name ec2-$(date +%s) --template-body file://ec2-param1.yml \ 
# --parameters "ParameterKey=InstanceType,ParameterValue=t2.small"

# Specifying the parameters in CLI can get a little bit unwieldy, so you can use a JSON file instead. 
# Here is the code from the JSON file and the command to launch it:

# params.json:
# [
#   {
#    "ParameterKey": "InstanceType",
#    "ParameterValue": "t2.small"
#  }
# ]

# aws cloudformation create-stack --stack-name ec2-$(date +%s) --template-body file://ec2-param1.yml --parameters file://params.json
