---
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: 'EC2-A1' # keypair must already exist
      ImageId: ami-030001f7dfbf357d1 # AMI us-east-1

# aws cloudformation create-stack --stack-name ec2 --template-body file://ec2.yml
# aws cloudformation describe-stacks --stack-name ec2